<!doctype html>
<html>
  <head>
    <title>Page title</title>
    <link rel="stylesheet"  href="/lgsf-dashboard/assets/css/styles.css">
    <style>



    </style>

  </head>
  <body>



    <div class="ds-page">
      <a class="ds-skip-link" href="#main">skip to content</a>

      <header class="ds-header">
        <a class="ds-skip-link" href="#main">skip to content</a>
        <a class="ds-logo" href="/lgsf-dashboard/">
          <img src="https://DemocracyClub.github.io/design-system/images/logo_icon.svg" alt="" />
          <span>LGSF Logbooks</span>
        </a>

      </header>


      <main id="main" tabindex="-1" class="ds-stack">

        
<style>

    pre {
        height:400px;
        overflow-x: scroll;
        width:100%
    }
</style>




  <h2 id="2022-03-10-11-24">2022-03-10</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>6 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-10 11:24:10.255418</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-10 11:24:16.896895</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>None: Max retries exceeded with url: //www.rbkc.gov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid/384/id/421/ScreenMode/Alphabetical/Default.aspx (Caused by None)</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:24:10] Fetching Scraper for: KEC                              handlers.py:22
           Begin attempting to scrape: KEC                        handlers.py:25
           Deleting existing data...                                 base.py:234
           Getting all files in KEC...                               base.py:186
           ...found 1 files in KEC                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:24:13] ...data deleted.                                          base.py:241
           Scraping from https://www.rbkc.gov.uk/council-and-democrac base.py:40
           y/councillors-and-committees/councillors/cllrs-ward/counci           
           llors-and-their-wards                                                
[11:24:16] Scraping from https://www.rbkc.gov.ukhttps://www.rbkc.gov. base.py:40
           uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid           
           /384/id/421/ScreenMode/Alphabetical/Default.aspx                     
           HTTPSConnectionPool(host='www.rbkc.gov.ukhttps',       handlers.py:34
           port=443): Max retries exceeded with url: //www.rbkc.g               
           ov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Per               
           son/mid/384/id/421/ScreenMode/Alphabetical/Default.asp               
           x (Caused by NewConnectionError('<urllib3.connection.H               
           TTPSConnection object at 0x7fe1763eb880>: Failed to                  
           establish a new connection: [Errno -2] Name or service               
           not known'))                                                         
           Finished attempting to scrape: KEC                        base.py:319
</pre>

  <h2 id="2022-03-10-00-07">2022-03-10</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>3 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-10 00:07:10.744132</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-10 00:07:14.554891</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>None: Max retries exceeded with url: //www.rbkc.gov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid/384/id/421/ScreenMode/Alphabetical/Default.aspx (Caused by None)</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[00:07:10] Fetching Scraper for: KEC                              handlers.py:22
           Begin attempting to scrape: KEC                        handlers.py:25
           Deleting existing data...                                 base.py:234
[00:07:11] Getting all files in KEC...                               base.py:186
           ...found 1 files in KEC                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[00:07:12] ...data deleted.                                          base.py:241
           Scraping from https://www.rbkc.gov.uk/council-and-democrac base.py:40
           y/councillors-and-committees/councillors/cllrs-ward/counci           
           llors-and-their-wards                                                
[00:07:14] Scraping from https://www.rbkc.gov.ukhttps://www.rbkc.gov. base.py:40
           uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid           
           /384/id/421/ScreenMode/Alphabetical/Default.aspx                     
           HTTPSConnectionPool(host='www.rbkc.gov.ukhttps',       handlers.py:34
           port=443): Max retries exceeded with url: //www.rbkc.g               
           ov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Per               
           son/mid/384/id/421/ScreenMode/Alphabetical/Default.asp               
           x (Caused by NewConnectionError('<urllib3.connection.H               
           TTPSConnection object at 0x7fcb4c3a0880>: Failed to                  
           establish a new connection: [Errno -2] Name or service               
           not known'))                                                         
           Finished attempting to scrape: KEC                        base.py:319
</pre>

  <h2 id="2022-03-08-11-41">2022-03-08</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>15 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-08 11:41:49.425627</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-08 11:42:04.550735</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>None: Max retries exceeded with url: //www.rbkc.gov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid/384/id/421/ScreenMode/Alphabetical/Default.aspx (Caused by None)</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:41:49] Fetching Scraper for: KEC                              handlers.py:22
           Begin attempting to scrape: KEC                        handlers.py:25
           Deleting existing data...                                 base.py:234
[11:41:50] Getting all files in KEC...                               base.py:186
           ...found 1 files in KEC                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:42:01] ...data deleted.                                          base.py:241
           Scraping from https://www.rbkc.gov.uk/council-and-democrac base.py:40
           y/councillors-and-committees/councillors/cllrs-ward/counci           
           llors-and-their-wards                                                
[11:42:04] Scraping from https://www.rbkc.gov.ukhttps://www.rbkc.gov. base.py:40
           uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid           
           /384/id/421/ScreenMode/Alphabetical/Default.aspx                     
           HTTPSConnectionPool(host='www.rbkc.gov.ukhttps',       handlers.py:34
           port=443): Max retries exceeded with url: //www.rbkc.g               
           ov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Per               
           son/mid/384/id/421/ScreenMode/Alphabetical/Default.asp               
           x (Caused by NewConnectionError('<urllib3.connection.H               
           TTPSConnection object at 0x7faef9b7dbb0>: Failed to                  
           establish a new connection: [Errno -2] Name or service               
           not known'))                                                         
           Finished attempting to scrape: KEC                        base.py:319
</pre>

  <h2 id="2022-03-07-11-51">2022-03-07</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>4 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-07 11:51:13.423822</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-07 11:51:18.134911</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>None: Max retries exceeded with url: //www.rbkc.gov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid/384/id/421/ScreenMode/Alphabetical/Default.aspx (Caused by None)</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:51:13] Fetching Scraper for: KEC                              handlers.py:22
           Begin attempting to scrape: KEC                        handlers.py:25
           Deleting existing data...                                 base.py:234
           Getting all files in KEC...                               base.py:186
           ...found 1 files in KEC                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:51:15] ...data deleted.                                          base.py:241
           Scraping from https://www.rbkc.gov.uk/council-and-democrac base.py:40
           y/councillors-and-committees/councillors/cllrs-ward/counci           
           llors-and-their-wards                                                
[11:51:17] Scraping from https://www.rbkc.gov.ukhttps://www.rbkc.gov. base.py:40
           uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid           
           /384/id/421/ScreenMode/Alphabetical/Default.aspx                     
           HTTPSConnectionPool(host='www.rbkc.gov.ukhttps',       handlers.py:34
           port=443): Max retries exceeded with url: //www.rbkc.g               
           ov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Per               
           son/mid/384/id/421/ScreenMode/Alphabetical/Default.asp               
           x (Caused by NewConnectionError('<urllib3.connection.H               
           TTPSConnection object at 0x7fd9e3145c40>: Failed to                  
           establish a new connection: [Errno -2] Name or service               
           not known'))                                                         
[11:51:18] Finished attempting to scrape: KEC                        base.py:319
</pre>

  <h2 id="2022-03-06-19-19">2022-03-06</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-06 19:19:54.736767</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-06 19:19:57.411914</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>None: Max retries exceeded with url: //www.rbkc.gov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid/384/id/421/ScreenMode/Alphabetical/Default.aspx (Caused by None)</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[19:19:54] Fetching Scraper for: KEC                              handlers.py:22
           Begin attempting to scrape: KEC                        handlers.py:25
           Deleting existing data...                                 base.py:234
[19:19:55] Getting all files in KEC...                               base.py:186
           KEC Does not exist                                        base.py:206
           ...no data to delete.                                     base.py:238
           Scraping from https://www.rbkc.gov.uk/council-and-democrac base.py:40
           y/councillors-and-committees/councillors/cllrs-ward/counci           
           llors-and-their-wards                                                
[19:19:56] Scraping from https://www.rbkc.gov.ukhttps://www.rbkc.gov. base.py:40
           uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid           
           /384/id/421/ScreenMode/Alphabetical/Default.aspx                     
[19:19:57] HTTPSConnectionPool(host='www.rbkc.gov.ukhttps',       handlers.py:34
           port=443): Max retries exceeded with url: //www.rbkc.g               
           ov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Per               
           son/mid/384/id/421/ScreenMode/Alphabetical/Default.asp               
           x (Caused by NewConnectionError('<urllib3.connection.H               
           TTPSConnection object at 0x7f6b6baa22e0>: Failed to                  
           establish a new connection: [Errno -2] Name or service               
           not known'))                                                         
           Finished attempting to scrape: KEC                        base.py:319
</pre>

  <h2 id="2022-03-06-17-41">2022-03-06</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>11 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-06 17:41:19.973342</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-06 17:41:31.746443</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>None: Max retries exceeded with url: //www.rbkc.gov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid/384/id/421/ScreenMode/Alphabetical/Default.aspx (Caused by None)</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[17:41:19] Fetching Scraper for: KEC                              handlers.py:21
           Begin attempting to scrape: KEC                        handlers.py:24
[17:41:20] Deleting existing data...                                 base.py:234
[17:41:21] Getting all files in KEC...                               base.py:186
           ...found 1 files in KEC                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[17:41:29] ...data deleted.                                          base.py:241
           Scraping from https://www.rbkc.gov.uk/council-and-democrac base.py:40
           y/councillors-and-committees/councillors/cllrs-ward/counci           
           llors-and-their-wards                                                
[17:41:31] Scraping from https://www.rbkc.gov.ukhttps://www.rbkc.gov. base.py:40
           uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid           
           /384/id/421/ScreenMode/Alphabetical/Default.aspx                     
           HTTPSConnectionPool(host='www.rbkc.gov.ukhttps',       handlers.py:33
           port=443): Max retries exceeded with url: //www.rbkc.g               
           ov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Per               
           son/mid/384/id/421/ScreenMode/Alphabetical/Default.asp               
           x (Caused by NewConnectionError('<urllib3.connection.H               
           TTPSConnection object at 0x7efcb382ab80>: Failed to                  
           establish a new connection: [Errno -2] Name or service               
           not known'))                                                         
           Finished attempting to scrape: KEC                        base.py:319
</pre>

  <h2 id="2022-03-05-20-10">2022-03-05</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>3 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-05 20:10:40.761763</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-05 20:10:43.890585</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>None: Max retries exceeded with url: //www.rbkc.gov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid/384/id/421/ScreenMode/Alphabetical/Default.aspx (Caused by None)</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[20:10:40] Fetching Scraper for: KEC                              handlers.py:21
           Begin attempting to scrape: KEC                        handlers.py:24
           Deleting existing data...                                 base.py:234
[20:10:41] Getting all files in KEC...                               base.py:186
           KEC Does not exist                                        base.py:206
           ...no data to delete.                                     base.py:238
           Scraping from https://www.rbkc.gov.uk/council-and-democrac base.py:40
           y/councillors-and-committees/councillors/cllrs-ward/counci           
           llors-and-their-wards                                                
[20:10:43] Scraping from https://www.rbkc.gov.ukhttps://www.rbkc.gov. base.py:40
           uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Person/mid           
           /384/id/421/ScreenMode/Alphabetical/Default.aspx                     
           HTTPSConnectionPool(host='www.rbkc.gov.ukhttps',       handlers.py:33
           port=443): Max retries exceeded with url: //www.rbkc.g               
           ov.uk/committees/Councillors/tabid/62/ctl/ViewCMIS_Per               
           son/mid/384/id/421/ScreenMode/Alphabetical/Default.asp               
           x (Caused by NewConnectionError('<urllib3.connection.H               
           TTPSConnection object at 0x7f31dfc13400>: Failed to                  
           establish a new connection: [Errno -2] Name or service               
           not known'))                                                         
           Finished attempting to scrape: KEC                        base.py:319
</pre>


      </main>
      <footer class="ds-footer">...</footer>
    </div>
  </body>
