<!doctype html>
<html>
  <head>
    <title>Page title</title>
    <link rel="stylesheet"  href="/lgsf-dashboard/assets/css/styles.css">
    <style>



    </style>

  </head>
  <body>



    <div class="ds-page">
      <a class="ds-skip-link" href="#main">skip to content</a>

      <header class="ds-header">
        <a class="ds-skip-link" href="#main">skip to content</a>
        <a class="ds-logo" href="/lgsf-dashboard/">
          <img src="https://DemocracyClub.github.io/design-system/images/logo_icon.svg" alt="" />
          <span>LGSF Logbooks</span>
        </a>

      </header>


      <main id="main" tabindex="-1" class="ds-stack">

        
<style>

    pre {
        height:400px;
        overflow-x: scroll;
        width:100%
    }
</style>




  <h2 id="2022-03-21-11-44">2022-03-21</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>12 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-21 11:44:18.924924</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-21 11:44:31.062251</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:44:30] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
[11:44:31] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-20-12-18">2022-03-20</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>22 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-20 12:18:12.690295</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-20 12:18:35.223514</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (InvalidTargetBranchException) when calling the MergeBranchesBySquash operation: Target branch parameter must point to either source or destination tip commit. Verify your target branch value is valid and then try again</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:18:29] Created log commit                                        base.py:376
           a072c61dadf096b049fba8916d048827eec3215e                             
           Attempting to create merge commit...                      base.py:281
[12:18:34] An error occurred (InvalidTargetBranchException) when  handlers.py:34
           calling the MergeBranchesBySquash operation: Target                  
           branch parameter must point to either source or                      
           destination tip commit. Verify your target branch                    
           value is valid and then try again                                    
[12:18:35] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-19-12-20">2022-03-19</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>7 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-19 12:20:46.354082</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-19 12:20:53.745378</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd></dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:20:46] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
[12:20:47] Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[12:20:53] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
           No new councillor data found.                             base.py:317
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-19-12-19">2022-03-19</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>3 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-19 12:19:49.019403</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-19 12:19:52.344918</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:19:49] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
           Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[12:19:50] ...data deleted.                                          base.py:241
           Scraping from                                              base.py:40
           http://www.shetland.gov.uk/about_your_councillors/                   
[12:19:52] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-19-12-01">2022-03-19</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>3 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-19 12:01:03.956787</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-19 12:01:07.496599</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:01:03] Fetching Scraper for: ZET                              handlers.py:22
[12:01:04] Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
           Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[12:01:05] ...data deleted.                                          base.py:241
           Scraping from                                              base.py:40
           http://www.shetland.gov.uk/about_your_councillors/                   
[12:01:07] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-18-11-39">2022-03-18</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>10 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-18 11:39:35.725173</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-18 11:39:45.943712</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:39:45] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-17-11-24">2022-03-17</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>14 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-17 11:24:50.107969</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-17 11:25:05.056634</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (InvalidTargetBranchException) when calling the MergeBranchesBySquash operation: Target branch parameter must point to either source or destination tip commit. Verify your target branch value is valid and then try again</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:24:57] Created log commit                                        base.py:376
           9099b34af3d31e3740c2e67f2cb84eaba11763f9                             
           Attempting to create merge commit...                      base.py:281
[11:25:04] An error occurred (InvalidTargetBranchException) when  handlers.py:34
           calling the MergeBranchesBySquash operation: Target                  
           branch parameter must point to either source or                      
           destination tip commit. Verify your target branch                    
           value is valid and then try again                                    
[11:25:05] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-16-11-25">2022-03-16</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>6 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-16 11:25:59.369441</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-16 11:26:06.204112</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd></dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:25:59] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
           Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:26:05] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
[11:26:06] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-16-11-18">2022-03-16</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-16 11:18:17.297950</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-16 11:18:25.342402</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:18:17] Fetching Scraper for: ZET                              handlers.py:22
[11:18:20] Begin attempting to scrape: ZET                        handlers.py:25
[11:18:21] Deleting existing data...                                 base.py:234
           Getting all files in ZET...                               base.py:186
[11:18:22] ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:18:23] ...data deleted.                                          base.py:241
           Scraping from                                              base.py:40
           http://www.shetland.gov.uk/about_your_councillors/                   
[11:18:25] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-15-11-56">2022-03-15</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-15 11:56:29.387146</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-15 11:56:38.282335</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd></dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:56:29] Fetching Scraper for: ZET                              handlers.py:22
[11:56:34] Begin attempting to scrape: ZET                        handlers.py:25
[11:56:35] Deleting existing data...                                 base.py:234
[11:56:36] Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:56:37] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
[11:56:38] No new councillor data found.                             base.py:317
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-15-11-55">2022-03-15</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>4 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-15 11:55:38.117566</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-15 11:55:42.536302</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:55:38] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
           Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:55:40] ...data deleted.                                          base.py:241
           Scraping from                                              base.py:40
           http://www.shetland.gov.uk/about_your_councillors/                   
[11:55:42] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-15-11-36">2022-03-15</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-15 11:36:39.160361</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-15 11:36:44.196682</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:36:39] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
           Getting all files in ZET...                               base.py:186
[11:36:40] ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:36:42] ...data deleted.                                          base.py:241
           Scraping from                                              base.py:40
           http://www.shetland.gov.uk/about_your_councillors/                   
[11:36:44] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-14-11-42">2022-03-14</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-14 11:42:23.197273</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-14 11:42:31.263241</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd></dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:42:23] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
[11:42:24] Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:42:30] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
[11:42:31] No new councillor data found.                             base.py:317
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-13-11-32">2022-03-13</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>12 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-13 11:32:30.868958</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-13 11:32:43.306456</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (InvalidTargetBranchException) when calling the MergeBranchesBySquash operation: Target branch parameter must point to either source or destination tip commit. Verify your target branch value is valid and then try again</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:32:38] Created log commit                                        base.py:376
           6fb5aa2dc4ddcae9ded56c5d90f2b72ae4c84ead                             
           Attempting to create merge commit...                      base.py:281
[11:32:42] An error occurred (InvalidTargetBranchException) when  handlers.py:34
           calling the MergeBranchesBySquash operation: Target                  
           branch parameter must point to either source or                      
           destination tip commit. Verify your target branch                    
           value is valid and then try again                                    
[11:32:43] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-13-00-05">2022-03-13</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-13 00:05:53.921646</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-13 00:06:02.880761</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[00:06:02] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-12-11-27">2022-03-12</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>6 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-12 11:27:27.827200</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-12 11:27:34.294594</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:27:27] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
[11:27:28] Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:27:32] ...data deleted.                                          base.py:241
           Scraping from                                              base.py:40
           http://www.shetland.gov.uk/about_your_councillors/                   
[11:27:34] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-11-11-28">2022-03-11</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-11 11:28:59.206172</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-11 11:29:05.041241</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd></dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:28:59] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
           Getting all files in ZET...                               base.py:186
[11:29:00] ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:29:04] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
[11:29:05] No new councillor data found.                             base.py:317
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-10-11-20">2022-03-10</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>7 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-10 11:20:24.465717</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-10 11:20:32.095445</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd></dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:20:24] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
[11:20:25] Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:20:31] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
[11:20:32] No new councillor data found.                             base.py:317
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-09-11-57">2022-03-09</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>22 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-09 11:57:03.095519</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-09 11:57:25.474891</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ConcurrentReferenceUpdateException) when calling the MergeBranchesBySquash operation: The merge cannot be completed because the following branch has been modified: refs/heads/main. Another user might have modified this branch while the merge was in progress. Wait a few minutes, and then try again.</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:57:13] Created log commit                                        base.py:376
           897412257d00f9e18dc5d7c75d723229b40d0d85                             
           Attempting to create merge commit...                      base.py:281
[11:57:25] An error occurred (ConcurrentReferenceUpdateException) handlers.py:34
           when calling the MergeBranchesBySquash operation: The                
           merge cannot be completed because the following branch               
           has been modified: refs/heads/main. Another user might               
           have modified this branch while the merge was in                     
           progress. Wait a few minutes, and then try again.                    
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-08-11-42">2022-03-08</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>12 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-08 11:42:53.640813</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-08 11:43:06.203859</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (InvalidTargetBranchException) when calling the MergeBranchesBySquash operation: Target branch parameter must point to either source or destination tip commit. Verify your target branch value is valid and then try again</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:43:00] Created log commit                                        base.py:376
           eec125e0310ae74c6e43a4467f54c2a1a230fa4a                             
           Attempting to create merge commit...                      base.py:281
[11:43:05] An error occurred (InvalidTargetBranchException) when  handlers.py:34
           calling the MergeBranchesBySquash operation: Target                  
           branch parameter must point to either source or                      
           destination tip commit. Verify your target branch                    
           value is valid and then try again                                    
[11:43:06] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-07-12-03">2022-03-07</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>26 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-07 12:03:01.576140</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-07 12:03:28.567021</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ConcurrentReferenceUpdateException) when calling the MergeBranchesBySquash operation: The merge cannot be completed because the following branch has been modified: refs/heads/main. Another user might have modified this branch while the merge was in progress. Wait a few minutes, and then try again.</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:03:14] Created log commit                                        base.py:376
           a1be30b4b933e9fd75a0118d63a19eeab9e2ec5e                             
           Attempting to create merge commit...                      base.py:281
[12:03:28] An error occurred (ConcurrentReferenceUpdateException) handlers.py:34
           when calling the MergeBranchesBySquash operation: The                
           merge cannot be completed because the following branch               
           has been modified: refs/heads/main. Another user might               
           have modified this branch while the merge was in                     
           progress. Wait a few minutes, and then try again.                    
           Finished attempting to scrape: ZET                        base.py:319
</pre>


      </main>
      <footer class="ds-footer">...</footer>
    </div>
  </body>
